# Generated by Django 5.1.1 on 2024-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('chose_date', models.CharField(max_length=200)),
                ('descrption', models.CharField(max_length=10000)),
            ],
        ),
    ]
