# Generated by Django 5.1.1 on 2024-11-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_appointment_getappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getappointment',
            name='descrption',
            field=models.TextField(default=''),
        ),
    ]
