# Generated by Django 5.1.1 on 2024-11-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_regdoctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdoctors',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='regdoctors',
            name='deperment',
        ),
        migrations.RemoveField(
            model_name='regdoctors',
            name='location',
        ),
    ]
