# Generated by Django 5.1.1 on 2024-11-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_regdoctors_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdoctors',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
