# Generated by Django 5.1.1 on 2024-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_regdoctors_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdoctors',
            name='is_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
