# Generated by Django 5.1.1 on 2024-11-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_regdoctors_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='app/img/drDP')),
                ('title', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=500)),
                ('livesIn', models.CharField(max_length=200)),
                ('WorkAt', models.CharField(max_length=200)),
                ('form', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=600)),
                ('x', models.CharField(max_length=600)),
                ('linkedin', models.CharField(max_length=600)),
            ],
        ),
    ]
