# Generated by Django 5.1.1 on 2024-11-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_drinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinfo',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
