# Generated by Django 5.1.1 on 2024-11-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_drinfo_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinfo',
            old_name='WorkAt',
            new_name='froms',
        ),
        migrations.RenameField(
            model_name='drinfo',
            old_name='form',
            new_name='workAt',
        ),
    ]
