# Generated by Django 5.1.1 on 2024-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_workat_drinfo_froms_rename_form_drinfo_workat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinfo',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='degree',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='facebook',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='froms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='linkedin',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='livesIn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='workAt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drinfo',
            name='x',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
