# Generated by Django 5.1.1 on 2024-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_drinfo_contact_alter_drinfo_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdoctors',
            name='contact',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='degree',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='facebook',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='froms',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='linkedin',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='livesIn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='profile',
            field=models.ImageField(default='', upload_to='app/img/drDP'),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='workAt',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='regdoctors',
            name='x',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.DeleteModel(
            name='DrInfo',
        ),
    ]
