# Generated by Django 5.1.1 on 2024-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_regdoctors_contact_regdoctors_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='app/img/pateint')),
            ],
        ),
    ]
