# Generated by Django 5.1.1 on 2024-11-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_patinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='patinet',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
