# Generated by Django 5.1.1 on 2024-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_patinet_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='getappointment',
            name='visit',
            field=models.CharField(default='', max_length=200),
        ),
    ]
