# Generated by Django 5.1.1 on 2024-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patinet',
            name='password',
        ),
        migrations.RemoveField(
            model_name='regdoctors',
            name='password',
        ),
        migrations.AddField(
            model_name='getappointment',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
