# Generated by Django 5.1.1 on 2024-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_patinet_password_remove_regdoctors_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getappointment',
            name='password',
        ),
        migrations.AddField(
            model_name='usermaster',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
