# Generated by Django 5.1.1 on 2024-12-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_getappointment_password_usermaster_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdoctors',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='regdoctors',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='regdoctors',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='regdoctors',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regdoctors',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
