# Generated by Django 5.1.1 on 2024-12-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_regdoctors_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdoctors',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
